# Generated by Django 4.0.4 on 2022-05-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
