# Generated by Django 4.0.4 on 2022-05-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_alter_contato_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='contato',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(max_length=50),
        ),
    ]
