# Generated by Django 4.0.4 on 2022-05-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_alter_contato_email_alter_contato_sobrenome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
