# Generated by Django 4.0.4 on 2022-05-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0005_alter_contato_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
