# Generated by Django 4.0.4 on 2022-05-17 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0006_contato_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='img',
        ),
    ]
